#!/usr/bin/env bash
# scripts/agent/create-pr.sh
#
# Creates a feature branch, commits agent changes, pushes, and opens a PR.
#
# Usage: ./create-pr.sh <issue_number> <task_id> <issue_dir> <logs_dir>
#
#   <issue_number>  — GitHub issue number (e.g., 7)
#   <task_id>       — Task identifier (e.g., TASK-001) or "auto"
#   <issue_dir>     — directory produced by extract-issue.sh (contains issue-title.txt)
#   <logs_dir>      — directory containing check-results.txt from CI checks
#
# Requires: gh CLI authenticated with repo write + PR create permissions.

set -euo pipefail

ISSUE_NUMBER="${1:?Usage: create-pr.sh <issue_number> <task_id> <issue_dir> <logs_dir>}"
TASK_ID="${2:?Usage: create-pr.sh <issue_number> <task_id> <issue_dir> <logs_dir>}"
ISSUE_DIR="${3:?Usage: create-pr.sh <issue_number> <task_id> <issue_dir> <logs_dir>}"
LOGS_DIR="${4:?Usage: create-pr.sh <issue_number> <task_id> <issue_dir> <logs_dir>}"

# --- Derive names ---
ISSUE_TITLE=""
if [ -f "$ISSUE_DIR/issue-title.txt" ]; then
  ISSUE_TITLE=$(cat "$ISSUE_DIR/issue-title.txt")
fi

# Normalize task_id for branch name (lowercase, hyphens)
TASK_SLUG=$(echo "$TASK_ID" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')
BRANCH_NAME="agent/${ISSUE_NUMBER}-${TASK_SLUG}"

# Derive conventional commit scope from task_id and issue title
# e.g., TASK-001 about TraceEvent types → feat(core): implement TraceEvent type definitions
derive_commit_message() {
  local title="$ISSUE_TITLE"
  local tid="$TASK_ID"

  # Determine scope from title keywords
  local scope="core"
  case "$title" in
    *policy*|*Policy*|*YAML*|*matcher*|*evaluator*) scope="policy" ;;
    *replay*|*Replay*|*golden*|*Golden*) scope="replay" ;;
    *CLI*|*cli*|*command*) scope="cli" ;;
    *adapter*|*Adapter*|*OpenClaw*) scope="adapters" ;;
    *CI*|*workflow*|*monorepo*|*bootstrap*|*Bootstrap*) scope="infra" ;;
  esac

  # Determine type from title keywords
  local ctype="feat"
  case "$title" in
    *fix*|*Fix*|*bug*|*Bug*) ctype="fix" ;;
    *test*|*Test*) ctype="test" ;;
    *refactor*|*Refactor*) ctype="refactor" ;;
    *doc*|*Doc*) ctype="docs" ;;
    *chore*|*Chore*|*bootstrap*|*Bootstrap*|*CI*) ctype="chore" ;;
  esac

  # Strip the TASK-XXX: prefix from the title for the message
  local description
  description=$(echo "$title" | sed 's/^TASK-[0-9]*[a-z]*:\s*//' | tr '[:upper:]' '[:lower:]')

  echo "${ctype}(${scope}): ${description}"
}

COMMIT_MSG=$(derive_commit_message)

echo "::group::Creating PR"
echo "  Branch:  $BRANCH_NAME"
echo "  Commit:  $COMMIT_MSG"
echo "  Issue:   #$ISSUE_NUMBER"

# --- Safety: refuse to touch main/master ---
CURRENT_BRANCH=$(git branch --show-current)
if [ "$CURRENT_BRANCH" = "main" ] || [ "$CURRENT_BRANCH" = "master" ]; then
  echo "Currently on $CURRENT_BRANCH — creating new branch."
fi

# Create and switch to branch
git checkout -b "$BRANCH_NAME"

# Stage all changes
git add -A

# Check if there are changes to commit
if git diff --cached --quiet; then
  echo "No changes to commit. Agent produced no file modifications."
  echo "::endgroup::"
  exit 0
fi

# --- Build the commit message body ---
CHANGED_FILES=$(git diff --cached --name-only)

COMMIT_BODY="${COMMIT_MSG}

Implements #${ISSUE_NUMBER}

Files changed:
$(echo "$CHANGED_FILES" | sed 's/^/- /')
"

# Commit
git commit -m "$COMMIT_BODY"

# Push
git push -u origin "$BRANCH_NAME"

# --- Build PR body ---
CHECK_RESULTS=""
if [ -f "$LOGS_DIR/check-results.txt" ]; then
  CHECK_RESULTS=$(cat "$LOGS_DIR/check-results.txt")
fi

PR_BODY_FILE=$(mktemp)
cat > "$PR_BODY_FILE" <<EOF
## Summary

Automated implementation of **${ISSUE_TITLE}** (closes #${ISSUE_NUMBER}).

Generated by the Agent PR Bot via workflow_dispatch.

## Task

${TASK_ID}: ${ISSUE_TITLE}

## Files Changed

${CHANGED_FILES}

## Verification Results

${CHECK_RESULTS}

## Checks Run

- [x] pnpm typecheck
- [x] pnpm lint
- [x] pnpm test
- [x] pnpm build
- [x] Allowed files enforcement

## Review Notes

- This PR was generated by an automated agent. Please review carefully.
- Verify that only allowed files were modified.
- Confirm acceptance criteria are met.
- Check test coverage matches the issue requirements.
EOF

# Create PR
gh pr create \
  --title "${TASK_ID}: ${ISSUE_TITLE}" \
  --body-file "$PR_BODY_FILE" \
  --base main \
  --head "$BRANCH_NAME" 2>&1 || {
    echo "Warning: gh pr create failed. Branch was pushed. Create PR manually."
    rm -f "$PR_BODY_FILE"
    echo "::endgroup::"
    exit 1
  }

rm -f "$PR_BODY_FILE"

PR_URL=$(gh pr view "$BRANCH_NAME" --json url -q '.url' 2>/dev/null || echo "(unknown)")
echo ""
echo "PR created: $PR_URL"
echo "::endgroup::"
