/**
 * Sprint 4 edge case tests.
 *
 * Probes implementation boundaries, corner cases, and potential faults
 * discovered during code review.
 */

import { describe, test, expect, beforeEach } from "vitest";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  startSession,
  recordEvent,
  endSession,
  readTrace,
  computeTraceStats,
  destroySession,
  getActiveSessions,
  redactWithPatterns,
  computeHashChain,
  canonicalize,
} from "../../packages/core/src/index.js";
import type { PartialTraceEvent, TraceEvent } from "../../packages/core/src/index.js";
import { runStats, runPolicyTest } from "../../packages/cli/src/index.js";
import { routeCommand } from "../../packages/cli/src/router.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const GOLDEN_DIR = resolve(__dirname, "../golden");

let tempDir: string;

beforeEach(async () => {
  tempDir = await mkdtemp(join(tmpdir(), "krynix-edge-"));
  return async () => {
    await rm(tempDir, { recursive: true, force: true });
  };
});

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makePartial(
  eventType: string,
  payload: unknown,
  timestamp = "2025-01-15T14:00:01.000Z",
): PartialTraceEvent {
  return {
    event_type: eventType as PartialTraceEvent["event_type"],
    timestamp,
    parent_id: null,
    agent_id: "test-agent",
    payload,
    metadata: null,
  };
}

const BASE = {
  event_id: "evt-000",
  session_id: "test-session",
  sequence_num: 0,
  timestamp: "2025-01-15T14:00:00.000Z",
  parent_id: null,
  agent_id: "test-agent",
  redacted: false,
  prev_hash: "",
  event_hash: "",
  metadata: null,
  schema_version: "1.0.0",
} as const;

function makeBasicEvents(): TraceEvent[] {
  return [
    {
      ...BASE,
      event_type: "lifecycle",
      payload: { action: "session_start", context: { replay_seed: 42 } },
    } as unknown as TraceEvent,
    {
      ...BASE,
      event_id: "evt-001",
      sequence_num: 1,
      event_type: "tool_call",
      payload: { tool_name: "file_read", arguments: { path: "/tmp/test.txt" } },
    } as unknown as TraceEvent,
    {
      ...BASE,
      event_id: "evt-002",
      sequence_num: 2,
      timestamp: "2025-01-15T14:00:05.000Z",
      event_type: "lifecycle",
      payload: { action: "session_end" },
    } as unknown as TraceEvent,
  ];
}

async function writeTrace(dir: string, events: TraceEvent[]): Promise<string> {
  const path = join(dir, "trace.jsonl");
  const chained = computeHashChain(events);
  const lines = chained.map((e: TraceEvent) => canonicalize(e));
  await writeFile(path, lines.join("\n") + "\n");
  return path;
}

// ---------------------------------------------------------------------------
// 1. computeTraceStats edge cases
// ---------------------------------------------------------------------------

describe("computeTraceStats edge cases", () => {
  test("negative duration: session_end before session_start yields negative ms", async () => {
    // Clock skew or bad data: end timestamp is before start
    const outputPath = join(tempDir, "trace-neg.jsonl");
    const session = await startSession({
      agentId: "test-agent",
      replaySeed: 42,
      outputPath,
    });
    // Record with an old timestamp
    await recordEvent(session, makePartial("tool_call", {
      tool_name: "file_read",
      arguments: { path: "/tmp" },
    }, "2024-01-01T00:00:00.000Z"));
    await endSession(session);

    const events = await readTrace(outputPath);
    const stats = computeTraceStats(events);

    // duration_ms computes from session_start to session_end
    // Both are generated by the session manager using Date.now()
    // so they should be close together. This tests the nominal path.
    expect(stats.duration_ms).not.toBeNull();
    expect(typeof stats.duration_ms).toBe("number");
  });

  test("trace with only non-lifecycle events yields null duration", () => {
    // A trace fragment that somehow only has tool events
    const events: TraceEvent[] = [
      {
        ...BASE,
        event_type: "tool_call",
        payload: { tool_name: "file_read", arguments: { path: "/tmp" } },
      } as unknown as TraceEvent,
    ];

    const stats = computeTraceStats(events);
    expect(stats.duration_ms).toBeNull();
    expect(stats.event_count).toBe(1);
    expect(stats.tool_call_count).toBe(1);
  });

  test("trace with checkpoint lifecycle events does not affect duration", () => {
    // checkpoint is a valid lifecycle action that should NOT be treated as start/end
    const events: TraceEvent[] = [
      {
        ...BASE,
        event_type: "lifecycle",
        timestamp: "2025-01-15T14:00:00.000Z",
        payload: { action: "session_start", context: { replay_seed: 42 } },
      } as unknown as TraceEvent,
      {
        ...BASE,
        event_id: "evt-cp",
        sequence_num: 1,
        event_type: "lifecycle",
        timestamp: "2025-01-15T14:00:30.000Z",
        payload: { action: "checkpoint" },
      } as unknown as TraceEvent,
      {
        ...BASE,
        event_id: "evt-end",
        sequence_num: 2,
        event_type: "lifecycle",
        timestamp: "2025-01-15T14:00:10.000Z",
        payload: { action: "session_end" },
      } as unknown as TraceEvent,
    ];

    const stats = computeTraceStats(events);
    // Duration should be 10s (start to end), NOT 30s (start to checkpoint)
    expect(stats.duration_ms).toBe(10000);
    expect(stats.event_type_counts["lifecycle"]).toBe(3);
  });

  test("multiple session_end events: uses last session_end for duration", () => {
    const events: TraceEvent[] = [
      {
        ...BASE,
        event_type: "lifecycle",
        timestamp: "2025-01-15T14:00:00.000Z",
        payload: { action: "session_start", context: { replay_seed: 42 } },
      } as unknown as TraceEvent,
      {
        ...BASE,
        event_id: "evt-end1",
        sequence_num: 1,
        event_type: "lifecycle",
        timestamp: "2025-01-15T14:00:05.000Z",
        payload: { action: "session_end" },
      } as unknown as TraceEvent,
      {
        ...BASE,
        event_id: "evt-end2",
        sequence_num: 2,
        event_type: "lifecycle",
        timestamp: "2025-01-15T14:00:10.000Z",
        payload: { action: "session_end" },
      } as unknown as TraceEvent,
    ];

    const stats = computeTraceStats(events);
    // Should use the LAST session_end
    expect(stats.duration_ms).toBe(10000);
  });

  test("unknown event_type is counted in event_type_counts", () => {
    const events: TraceEvent[] = [
      {
        ...BASE,
        event_type: "custom_type" as TraceEvent["event_type"],
        payload: { data: "something" },
      } as unknown as TraceEvent,
    ];

    const stats = computeTraceStats(events);
    expect(stats.event_count).toBe(1);
    // The custom type should be tracked dynamically
    expect(stats.event_type_counts["custom_type"]).toBe(1);
    // Known types should all be 0
    expect(stats.event_type_counts["tool_call"]).toBe(0);
  });

  test("llm_response with zero tokens results in total_token_usage = 0", () => {
    const events: TraceEvent[] = [
      {
        ...BASE,
        event_type: "llm_response",
        payload: {
          model: "gpt-4",
          content: "",
          usage: { prompt_tokens: 0, completion_tokens: 0 },
          finish_reason: "stop",
        },
      } as unknown as TraceEvent,
    ];

    const stats = computeTraceStats(events);
    expect(stats.total_token_usage).toBe(0);  // 0, not null (llm_response exists)
  });
});

// ---------------------------------------------------------------------------
// 2. destroySession edge cases
// ---------------------------------------------------------------------------

describe("destroySession edge cases", () => {
  test("destroy then start a new session with the same seed works", async () => {
    const path1 = join(tempDir, "trace-d1.jsonl");
    const path2 = join(tempDir, "trace-d2.jsonl");

    const session1 = await startSession({
      agentId: "test-agent",
      replaySeed: 42,
      outputPath: path1,
    });
    await destroySession(session1);

    // Starting a new session with the same seed should work
    const session2 = await startSession({
      agentId: "test-agent",
      replaySeed: 42,
      outputPath: path2,
    });

    // Both sessions get the same deterministic ID
    expect(session2.sessionId).toBe(session1.sessionId);
    await endSession(session2);
    expect(getActiveSessions()).toBe(0);
  });

  test("concurrent destroy and endSession race: first wins, second is no-op or throws", async () => {
    const path = join(tempDir, "trace-race.jsonl");
    const session = await startSession({
      agentId: "test-agent",
      replaySeed: 42,
      outputPath: path,
    });

    // Both should succeed or gracefully handle the race
    await destroySession(session);
    // endSession should now throw because session was destroyed
    await expect(endSession(session)).rejects.toThrow();
    expect(getActiveSessions()).toBe(0);
  });
});

// ---------------------------------------------------------------------------
// 3. redactWithPatterns edge cases
// ---------------------------------------------------------------------------

describe("redactWithPatterns edge cases", () => {
  test("custom pattern matching built-in field: both apply, result is same", () => {
    // Custom pattern also matches api_key — shouldn't double-redact
    const event = {
      ...BASE,
      event_type: "tool_call" as const,
      payload: {
        tool_name: "test",
        arguments: { api_key: "sk-secret" },
      },
    } as unknown as TraceEvent;

    const result = redactWithPatterns(event, [{ pattern: "api_key" }]);
    const args = (result.payload as { arguments: Record<string, unknown> }).arguments;

    // Built-in fires first, so custom never reaches it — value should be redacted once
    expect(args["api_key"]).toMatch(/^\[REDACTED:[0-9a-f]{8}\]$/);
    // Should NOT be double-redacted (i.e., [REDACTED:...] redacted again)
    expect(args["api_key"]).not.toMatch(/^\[REDACTED:.*\[REDACTED:/);
  });

  test("already-redacted event: redacted flag preserved when no new matches", () => {
    const event = {
      ...BASE,
      redacted: true,  // already flagged
      event_type: "tool_call" as const,
      payload: {
        tool_name: "test",
        arguments: { name: "Alice" },
      },
    } as unknown as TraceEvent;

    const result = redactWithPatterns(event, [{ pattern: "^ssn$" }]);
    // No matches, but the existing redacted flag should be preserved
    expect(result.redacted).toBe(true);
  });

  test("empty string pattern matches all fields", () => {
    const event = {
      ...BASE,
      event_type: "tool_call" as const,
      payload: {
        tool_name: "test",
        arguments: { name: "Alice", age: "30" },
      },
    } as unknown as TraceEvent;

    // Empty string matches everything (regex "")
    const result = redactWithPatterns(event, [{ pattern: "" }]);
    const args = (result.payload as { arguments: Record<string, unknown> }).arguments;
    // All string values should be redacted because "" matches any string
    expect(args["name"]).toMatch(/^\[REDACTED:/);
    expect(args["age"]).toMatch(/^\[REDACTED:/);
  });

  test("deeply nested object redaction works (3+ levels)", () => {
    const event = {
      ...BASE,
      event_type: "tool_call" as const,
      payload: {
        tool_name: "test",
        arguments: {
          level1: {
            level2: {
              level3: {
                ssn: "123-45-6789",
                safe: "visible",
              },
            },
          },
        },
      },
    } as unknown as TraceEvent;

    const result = redactWithPatterns(event, [{ pattern: "^ssn$" }]);
    const args = (result.payload as { arguments: Record<string, unknown> }).arguments;
    const l1 = args["level1"] as Record<string, unknown>;
    const l2 = l1["level2"] as Record<string, unknown>;
    const l3 = l2["level3"] as Record<string, unknown>;
    expect(l3["ssn"]).toMatch(/^\[REDACTED:/);
    expect(l3["safe"]).toBe("visible");
  });

  test("null payload does not crash scanObject", () => {
    const event = {
      ...BASE,
      event_type: "lifecycle" as const,
      payload: { action: "session_start", context: { replay_seed: 42 } },
    } as unknown as TraceEvent;

    // Should not throw — lifecycle payloads have a different shape
    const result = redactWithPatterns(event, [{ pattern: "^ssn$" }]);
    expect(result).toBeDefined();
  });
});

// ---------------------------------------------------------------------------
// 4. Router policy namespace edge cases
// ---------------------------------------------------------------------------

describe("Router policy namespace edge cases", () => {
  test("policy test with --help before test subcommand shows help", async () => {
    const result = await routeCommand(["policy", "--help", "test"]);
    // --help takes priority over subcommand
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("--policy");
  });

  test("policy with no subcommand shows namespace help", async () => {
    const result = await routeCommand(["policy"]);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("policy test");
  });

  test("policy test --help shows help, not error", async () => {
    const result = await routeCommand(["policy", "test", "--help"]);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("--policy");
    expect(result.stdout).toContain("--trace");
  });

  test("flags before 'test' subcommand are passed through correctly", async () => {
    // "policy --trace foo.jsonl test --policy bar.yaml" — --trace comes before test
    const tracePath = await writeTrace(tempDir, makeBasicEvents());
    const policyPath = join(tempDir, "allow.policy.yaml");
    await writeFile(policyPath, `
apiVersion: krynix.dev/v1
kind: Policy
metadata:
  name: allow-all
  version: "1.0.0"
  description: Allow everything
spec:
  scope:
    agents: ["*"]
    event_types: ["*"]
  rules:
    - id: allow-all
      description: Allow all events
      match:
        payload: []
      action: allow
      severity: info
      message: Allowed
`);

    // Flags before "test" are included in rest, then test is stripped
    const result = await routeCommand([
      "policy",
      "--trace", tracePath,
      "test",
      "--policy", policyPath,
    ]);
    // Should work — both --trace and --policy should be passed to runPolicyTest
    expect(result.exitCode).toBe(0);
    const output = JSON.parse(result.stdout);
    expect(output.verdict).toBeDefined();
  });
});

// ---------------------------------------------------------------------------
// 5. CLI stats edge cases
// ---------------------------------------------------------------------------

describe("CLI stats edge cases", () => {
  test("stats on empty trace file exits with error", async () => {
    const emptyPath = join(tempDir, "empty.trace.jsonl");
    await writeFile(emptyPath, "");

    const result = await runStats(["--trace", emptyPath]);
    // Empty trace should parse to 0 events, not error
    expect(result.exitCode).toBe(0);
    expect(result.stats).not.toBeNull();
    expect(result.stats?.event_count).toBe(0);
  });

  test("stats --trace value is another flag: treated as missing file", async () => {
    // --trace --help — getArg returns "--help" as the trace path
    const result = await runStats(["--trace", "--nonexistent-path"]);
    expect(result.exitCode).toBe(1);
    expect(result.error).toContain("Failed to read trace");
  });
});

// ---------------------------------------------------------------------------
// 6. CLI policy test edge cases
// ---------------------------------------------------------------------------

describe("CLI policy test edge cases", () => {
  test("policy test with empty trace processes without crash", async () => {
    const emptyTracePath = join(tempDir, "empty.trace.jsonl");
    await writeFile(emptyTracePath, "");

    const policyPath = join(tempDir, "allow.policy.yaml");
    await writeFile(policyPath, `
apiVersion: krynix.dev/v1
kind: Policy
metadata:
  name: allow-all
  version: "1.0.0"
  description: Allow everything
spec:
  scope:
    agents: ["*"]
    event_types: ["*"]
  rules:
    - id: allow-all
      description: Allow all events
      match:
        payload: []
      action: allow
      severity: info
      message: Allowed
`);

    const result = await runPolicyTest([
      "--policy", policyPath,
      "--trace", emptyTracePath,
    ]);
    expect(result.exitCode).toBe(0);
    expect(result.result).not.toBeNull();
    expect(result.result?.verdict).toBe("pass");
    expect(result.result?.violations).toHaveLength(0);
  });

  test("--expect-verdict with correct verdict but violations still exits 0", async () => {
    // A trace that causes violations, --expect-verdict fail should succeed
    const tracePath = await writeTrace(tempDir, makeBasicEvents());
    const policyPath = join(tempDir, "deny.policy.yaml");
    await writeFile(policyPath, `
apiVersion: krynix.dev/v1
kind: Policy
metadata:
  name: deny-all
  version: "1.0.0"
  description: Deny everything
spec:
  scope:
    agents: ["*"]
    event_types: ["*"]
  rules:
    - id: deny-all
      description: Deny all events
      match:
        payload: []
      action: deny
      severity: error
      message: Denied
`);

    const result = await runPolicyTest([
      "--policy", policyPath,
      "--trace", tracePath,
      "--expect-verdict", "fail",
    ]);
    expect(result.exitCode).toBe(0);
    expect(result.result?.expectation?.match).toBe(true);
    expect(result.result?.violations.length).toBeGreaterThan(0);
  });

  test("case-sensitive verdict comparison: 'PASS' is invalid", async () => {
    const result = await runPolicyTest([
      "--policy", "p.yaml",
      "--trace", "t.jsonl",
      "--expect-verdict", "PASS",
    ]);
    expect(result.exitCode).toBe(1);
    expect(result.error).toContain("Invalid --expect-verdict");
  });

  test("nonexistent policy file returns structured error", async () => {
    const tracePath = await writeTrace(tempDir, makeBasicEvents());
    const result = await runPolicyTest([
      "--policy", "/nonexistent/policy.yaml",
      "--trace", tracePath,
    ]);
    expect(result.exitCode).toBe(1);
    expect(result.error).toContain("Failed to read policy");
  });
});
